void InsertionSort(int *A, int length);
void Merge(int *A, int p, int q, int r);
void MergeSort(int *A, int p, int r);
void HeapSort(int *A, int length);
void QuickSort(int *A, int p, int r);
void BubbleSort(int* A, int length);
int Partition(int *A, int p, int r);
void Print(int *A, int p, int r);
void Randomize(int *A, int length);
void FillReverse(int *A, int length);
int PartitionAt(int *A, int p, int r, int k);
int Select(int *A, int i, int p, int r);