void InsertionSort(int *A, int length);
void Merge(int *A, int p, int q, int r);
void MergeSort(int *A, int p, int r);
void HeapSort(int *A, int size);
void QuickSort(int *A, int p, int r);
int Partition(int *A, int p, int r);
void PrintList(int *A, int start, int end);
int PartitionAt(int *A, int start, int end, int k);
int Median(int *A, int p, int r);
int Select(int *A, int i, int start, int end);